[2024-10-16 15:58:03,499] 71 root - INFO - DataFrame created successfully
[2024-10-16 15:58:03,499] 54 root - INFO - Exception Occured in load_object function utils
[2024-10-16 15:58:03,499] 29 root - ERROR - Exception occurred during prediction: Error occurred in Python script name [e:\data_science _master\ml\flight_prediction\src\FlightPricePrediction\utils\utils.py] line number [51] error message [[Errno 2] No such file or directory: 'artifacts\\preprocessor.pkl']
